### ISSUE TITLE
Slow Updating of Recent papers

### ISSUE THREAD

**Issue by JohannesAck** [karpathy/arxiv-sanity-preserver#109]
Currently the website lacks 4 days behind the actual arXiv publications.
I'm not sure why that is or what can be done about it, but it would be nice if it was more up to date.

**Comment by Randl** [comment]
Related issues:

https://github.com/karpathy/arxiv-sanity-preserver/issues/57
https://github.com/karpathy/arxiv-sanity-preserver/issues/72
https://github.com/karpathy/arxiv-sanity-preserver/issues/79
