### ISSUE TITLE
Flip color scheme of tabs

### ISSUE THREAD

**Issue by chrisfischer** [karpathy/arxiv-sanity-preserver#117]
I'm curious if any else feels like the color scheme of the tabs is a bit unintuitive. It seems logical for the selected tab to appear "attached" to the rest of the page, while the unselected ones are shadowed.

Current:
<img width="1097" alt="screen shot 2018-10-02 at 4 57 56 pm" src="https://user-images.githubusercontent.com/8304994/46376761-d48f7200-c664-11e8-9b0a-49f0c2a94ba8.png">

Proposed:
<img width="1087" alt="screen shot 2018-10-02 at 4 58 44 pm" src="https://user-images.githubusercontent.com/8304994/46376753-cccfcd80-c664-11e8-8585-50659cc86a3d.png">

**Comment by karpathy** [comment]
Implemented quite easily with https://github.com/karpathy/arxiv-sanity-preserver/commit/4a2b7db6a0ed16b0740de0aaf0170fbeca331358 , thank you! closing.
