### ISSUE TITLE
Image Magic not authorized errors while running 

### ISSUE THREAD

**Issue by pranayaryal** [karpathy/arxiv-sanity-preserver#118]
While running `python thumb_pdf.py`, was getting "not authorized errors" from image magick.

**Comment by pranayaryal** [comment]
This link https://stackoverflow.com/questions/42928765/convertnot-authorized-aaaa-error-constitute-c-readimage-453 helped.

**Comment by karpathy** [comment]
Happy to hear you've resolved it, thank you for posting the solution.
