### ISSUE TITLE
"Could not render: incorrectly formatted pdf" error on every recent paper

### ISSUE THREAD

**Issue by jasonjmcghee** [karpathy/arxiv-sanity-preserver#135]
![image](https://user-images.githubusercontent.com/1522149/73142983-9f711500-4049-11ea-9666-5a0e84cec4da.png)

**Comment by markus-flicke** [comment]
It appears to me that pdftotext is not working for recent papers anymore. Hence ASP cannot parse PDFs...

**Comment by black-puppydog** [comment]
so is that a change on the arxiv side (how they build the pdfs) or in the pdftotext version (if that change on the server?)

**Comment by jasonjmcghee** [comment]
This issue appears to be fixed.

**Comment by black-puppydog** [comment]
do we know what caused this in the end?

**Comment by karpathy** [comment]
The issue was with thumbnail generation, `convert` was failing with an error. Had to adjust system configuration files, no code changes. Still slightly mysterious why it happened rather suddenly without any (manual) system update or anything.

**Comment by black-puppydog** [comment]
you wouldn't happen to be running `unattended-upgrades` or such? :)
