### ISSUE TITLE
All recent paper thumbnails getting 404s

### ISSUE THREAD

**Issue by jasonjmcghee** [karpathy/arxiv-sanity-preserver#141]
All recent paper thumbnails are getting 404s.

![image](https://user-images.githubusercontent.com/1522149/83436554-e81f4d00-a3f2-11ea-8962-fcc518bcbf6d.png)

**Comment by jasonjmcghee** [comment]
Appears to be resolved.

**Comment by karpathy** [comment]
I didn't even do anything. That's how much this all needs a rewrite :D
