### ISSUE TITLE
No such file or directory: 'db2.p'

### ISSUE THREAD

**Issue by HugangR** [karpathy/arxiv-sanity-preserver#142]
Hi 

When I run this command
python3 serve.py --prod --port 80

it gives me this error message:

loading the paper database db2.p
Traceback (most recent call last):
  File "serve.py", line 658, in <module>
    db = pickle.load(open(Config.db_serve_path, 'rb'))
FileNotFoundError: [Errno 2] No such file or directory: 'db2.p'

Did I miss any step? Which step is supposed to generate 'db2.p' file? Why is it not found?

Best regards,
Hugang

**Comment by karelin** [comment]
This file should be generated by `make_cache.py` script.
I'd would advise to check all the code of project before running it: it is about 2000 lines and would take couple of hours to understand all nuts and bolts ;)

**Comment by HugangR** [comment]
> This file should be generated by `make_cache.py` script.
> I'd would advise to check all the code of project before running it: it is about 2000 lines and would take couple of hours to understand all nuts and bolts ;)

Thank you, it is working now!
