### ISSUE TITLE
Would it be acceptable to the team if I redesign and code the UI/UX part of the website?

### ISSUE THREAD

**Issue by imflash217** [karpathy/arxiv-sanity-preserver#145]
Hi,
Thanks for such a great toolkit for us researchers. I still feel that the UI part of the site can be heavily improved for easy accessibility. Would it be acceptable to the team if I redesign and code the UI/UX part of the website? I can file a PR for review after I redesign it. I am asking it before starting the work to make sure that I am thinking in the right direction.
Thanks.

**Comment by MohamedAliRashad** [comment]
@imflash217 attach examples for the design you are thinking
