### ISSUE TITLE
shutdown the project?

### ISSUE THREAD

**Issue by iperov** [karpathy/arxiv-sanity-preserver#170]
the site is down very oftern. It is better to close the project.

**Comment by sugarlemons** [comment]
I can't visit the site today.

**Comment by Syzygianinfern0** [comment]
It's back up right now

**Comment by Syzygianinfern0** [comment]
@enricoros https://www.reddit.com/r/learnmachinelearning/comments/o7l9sv/how_to_read_more_research_papers/?utm_source=share&utm_medium=web2x&context=3

**Comment by MohamedAliRashad** [comment]
It's down now

**Comment by enricoros** [comment]
Is the project not shut down anymore?! the project had huge value and the -lite version doesn't compare.

**Comment by davidhuangal** [comment]
What a huge disappointment this all is.
