### ISSUE TITLE
Add Mathjax/KaTeX to display math content

### ISSUE THREAD

**Issue by ibab** [karpathy/arxiv-sanity-preserver#20]
As the text already contains `$` and LaTeX code everywhere, it should be quite simple to display it properly using mathjax, or the very cool [KaTeX](https://khan.github.io/KaTeX/).

Mathjax instructions: https://docs.mathjax.org/en/v2.6-latest/start.html
KaTeX instructions: https://github.com/Khan/KaTeX/blob/master/contrib/auto-render/README.md

See here for a version of the sanity-preserver that uses Mathjax: https://arxiv.babushk.in/.

**Comment by karpathy** [comment]
Very nice to see that you got it running!! Thanks for the links, I might incorporate sometime when I can steal some time.

**Comment by karpathy** [comment]
Added this suggestion with the most recent commit. Thank you!
