### ISSUE TITLE
Would it be useful to have an extension to this project where you can see the ancestors and predecessors of a research paper?

### ISSUE THREAD

**Issue by syed-ahmed** [karpathy/arxiv-sanity-preserver#22]
For instance, I'm reading this paper and I see it referred to ideas from previously published papers. I want to put this paper as a child of those research papers and maintain a tree so that I can keep track of the ideas from the paper in a systematic manner to aid my research. In other words, I want to visualize the path of knowledge that flows from one research paper to another.

**Comment by karpathy** [comment]
I think your'e referring to something along lines of what I did with Research Lei a while ago:
http://cs.stanford.edu/people/karpathy/researchlei/

basically for every paper there were (on left) all papers that it cites, and also (on right) all papers that cite it, sorted by various things, including author names. This was a nice way to see the evolution.

Problem here is that it's tricky to extract the citations from the pdfs. Not impossible, but kind of tricky. With the citation graph one could then do something along these lines, possibly.

Another option might be to base it purely on L2 similarities as right now, but also on author names: e.g. a very similar paper from the same authors likely inspired this paper. Could look into maybe.

**Comment by syed-ahmed** [comment]
I stumbled upon your project and then read the microsoft api got shut down... It would have been awesome if those bibliography could come in a RESTful api. What do you mean by L2 similarities?

**Comment by moon05** [comment]
Do you think we could start working on it?

**Comment by karelin** [comment]
Btw, there is a free API from semanticscholar for backward/forward references, for example it is used by Bibex, https://labs.arxiv.org/projects/bibexplorer, as used at every arXiv page.

Also, there is opencitations project (there is an API and download).
