### ISSUE TITLE
Any plans for adding feature of showing number of citations?

### ISSUE THREAD

**Issue by ffmpbgrnn** [karpathy/arxiv-sanity-preserver#3]

**Comment by karpathy** [comment]
this is not currently part of returned information from arxiv, which makes it tricky information to obtain. If you have ideas I'd be happy to hear them

**Comment by ffmpbgrnn** [comment]
Get citations from Google Scholar, save them as meta just like another attributes, and update citations every month? [scholar.py](https://github.com/ckreibich/scholar.py) provides simple APIs.

**Comment by karpathy** [comment]
cool, i got it running. I'll add this in next release, thanks for the idea.

**Comment by karpathy** [comment]
It turns out Google **REALLY** does not want you scraping scholar, and rate limits aggressively. This feature is impossible for now. Closing issue.
