### ISSUE TITLE
Can not start webserver. No such table in database.

### ISSUE THREAD

**Issue by plus13** [karpathy/arxiv-sanity-preserver#31]
Hi, sorry for my poor bug report. I'm new with github und such.
I'm trying to use your program with two topics in the astrophysics domain.
Everything processed fine until the webserver-like thing tries to read some tables.

~/arxiv-sanity-preserver ❯❯❯ ./venv/bin/python serve.py --prod
/$HOME/arxiv-sanity-preserver/venv/lib/python2.7/site-packages/flask_limiter/extension.py:124: UserWarning: Use of the default `get_ipaddr` function is discouraged. Please refer to https://flask-limiter.readthedocs.org/#rate-limit-domain for the recommended configuration
  UserWarning
Namespace(num_results=200, port=5000, prod=True)
loading db.p...
loading tfidf_meta.p...
loading sim_dict.p...
loading user_sim.p...
precomputing papers date sorted...
computing top papers...
Traceback (most recent call last):
  File "serve.py", line 415, in <module>
    top_counts = get_popular()
  File "serve.py", line 409, in get_popular
    libs = sqldb.execute('''select * from library''').fetchall()
sqlite3.OperationalError: no such table: library

**Comment by karpathy** [comment]
Oh sorry! I think this is not well documented. Can you try `sqlite3 as.db < schema.sql` ? this initializes the database, which looks to be missing for you right now.

**Comment by plus13** [comment]
Worked for me. Thank you!

**Comment by karpathy** [comment]
Great to hear! Closing the issue and will push a Readme patch addressing this. Thanks and I hope your arxiv-sanity fork in astrophysics works nicely!
