### ISSUE TITLE
System for sharing libraries

### ISSUE THREAD

**Issue by robertostling** [karpathy/arxiv-sanity-preserver#32]
This is a great tool, and I was thinking about extending it with paper archives beyond arXiv. But if everyone set up their own version of arxiv-sanity, the benefit of having access to other users' libraries for the recommendation system disappears.

Would you consider a system for exporting the library database? I guess something as simple as providing a regular static dump of DOI sets corresponding to anonymized libraries would be a good start. Then every admin of an arxiv-sanity setup (or other tools for that matter) can benefit from the user base of others.

**Comment by karpathy** [comment]
The entire database is stored inside `as.db`, so it is easy to ship around different arxiv sanity forks.
