### ISSUE TITLE
Hosting "fork" for physics categories

### ISSUE THREAD

**Issue by Moredread** [karpathy/arxiv-sanity-preserver#33]
I'm started indexing some of the Physics categories. My plan is to cover all of them, but I've started with physics.\* and astro-ph.\* for now.

The site is currently hosted at http://physics.arxiv-sanity.nolife.de/

I'd be wiling to host it long term, if you want to focus on the already covered categories. Alternatively I could forward the PDFs, thumbnails and extracted texts to you, if you want to incorporate them in your site. What is your plan at the moment?

How do you want to handle domain names for forks? As a sub domain, or should I register a different one?

**Comment by karpathy** [comment]
Hi @Moredread looks great! I'm not interested in hosting this right now personally. I think I rather prefer having arxiv-sanity per small community, so that "top" papers make sense, for example.

I don't have strong opinions on the domain names. Looks good and keep me in the loop on how it goes!

**Comment by Moredread** [comment]
I'ver registered and set up http://arxiv-sanity-physics.com/ in the mean time.

**Comment by karpathy** [comment]
nice! looks great! :)

**Comment by michaelmior** [comment]
It would be nice if there were a list of forks somewhere, perhaps on the GitHub README. I just put up [DB Sanity](https://www.db-sanity.com/) yesterday for cs.DB and cs.IR.

**Comment by yottamoe** [comment]
Hi Moredread, do you still manage the arxiv-sanity-physics website? The link doesn't work at the moment.

**Comment by Moredread** [comment]
@yottamoe yeah, somehow my updating script broke in march I think and I have to sync up the database manually. I'll see if I can get it working again next week and will try to set up monitoring so that will not happen again. Sorry, I had very little free time in the last few months. :/

**Comment by ad48** [comment]
I adapted ASP to content from general relativity a while ago. I included an ORCID OAuth2.0 login so that users would have a bit more security and I think it might have done some personalised recommendations too. https://github.com/ad48/asp The ORCID login might be a useful feature.
