### ISSUE TITLE
Add a LICENSE file, please.

### ISSUE THREAD

**Issue by bskaggs** [karpathy/arxiv-sanity-preserver#37]
Is arxiv-sanity-preserver under an open source license?  Can we [make modifications and contribute back](https://help.github.com/articles/open-source-licensing/#what-happens-if-i-dont-choose-a-license)?

**Comment by karpathy** [comment]
yes it's MIT license

**Comment by michaelmior** [comment]
@karpathy Would you mind add a `LICENSE.md` or some mention in the README to make this more explicit?

**Comment by karpathy** [comment]
Done with a recent commit. Marking closed.
