### ISSUE TITLE
Integrate with Short Science / GitXiv

### ISSUE THREAD

**Issue by hans** [karpathy/arxiv-sanity-preserver#45]

**Comment by ieee8023** [comment]
I'm from ShortScience.org. We can add a link to http://www.arxiv-sanity.com/ARXIVID for every arxiv paper. I think we can also add a link to save it on arxiv-sanity. We can also add the page images under the title on ShortScience.org. We are open to ideas. 

Papers can be looked up by a GET request to http://www.shortscience.org/paper?bibtexKey=ARXIVID It will return an HTTP 200 status only if there are summaries.

**Comment by karpathy** [comment]
Hi Joseph, I like what ShortScience is doing! I wanted to review my very first paper (in ACL) on [WikiReading](http://www.aclweb.org/anthology/P/P16/P16-1145.pdf) there today but unfortunately it's not in database :( 

That aside, I'd be happy to integrate with ShortScience.org. arxiv-sanity uses a very simple URL scheme, e.g. `http://www.arxiv-sanity.com/1603.05279`. The value proposition here is that arxiv-sanity recommends similar papers. Adding it to library is one click from there, so probably doesn't need to be included from your site explicitly.

In turn, I'd love to somehow integrate or at least link to shortscience.org from arxiv-sanity. I don't know what the preferred way would be here. Ideally I'd like to include a link to each paper, maybe along the lines of "see reviews on ShortScience (3)", e.g. indicating 3 reviews for that paper.

I'd be slightly concerned about creating so many GET requests though, one per paper. One possible extension to your API you might consider is to add batch requesting, which could allow me to pull data from multiple papers at one time.

**Comment by ieee8023** [comment]
Thanks!

The WikiReading paper is not in any of the data providers that we are using yet because it is so new. If it had a DOI or if it was on arXiv it would show up. We are working on allowing users to add papers but it is going very slow. I added it manually: http://www.shortscience.org/paper?bibtexKey=hewlettwikireading

There is now an arxiv-sanity.com link on every arXiv paper: http://www.shortscience.org/venue?key=journals/corr

How about if that info is exposed using an RSS feed? We could have an rss-full.xml that would have all summaries and metadata for each summary?

**Comment by ieee8023** [comment]
This endpoint is live now: http://www.shortscience.org/rss-all.xml

If the summary is from an arXiv paper it will have an extra tag "shortscience:arxivid" that contains the arXiv id!

**Comment by karpathy** [comment]
completed a very simple integration that links to the shortscience page for each paper. don't have time for more at the moment. thanks! closing for now.

**Comment by ieee8023** [comment]
Couldn't sleep so I added a popover when the mouse hovers over the arxiv-sanity link. I'm linking to the images on arxiv-sanity. Let me know if you don't want images linked like this and I can get rid of it.

<img width="769" alt="screen shot 2016-08-23 at 12 21 33 am" src="https://cloud.githubusercontent.com/assets/446367/17880369/017c32be-68c8-11e6-8ed9-27e3e0c40768.png">
