### ISSUE TITLE
UI bug with overlapping "Fork me on github" banner

### ISSUE THREAD

**Issue by ludwigschubert** [karpathy/arxiv-sanity-preserver#63]
At certain screen widths the "Fork me on github" banner overlays the paper's PDF button.

*Normal case*:
<img width="269" alt="screen shot 2017-03-06 at 8 18 37 pm" src="https://cloud.githubusercontent.com/assets/1167977/23641640/5a07edb6-02aa-11e7-8aa2-efb4afb2d4e2.png">

*Problematic case*:
<img width="213" alt="screen shot 2017-03-06 at 8 18 45 pm" src="https://cloud.githubusercontent.com/assets/1167977/23641638/59f1e804-02aa-11e7-9903-5861f6e823cc.png">

I'd be happy to help solving if there's interest and no ongoing UI rework already.

**Comment by karpathy** [comment]
thanks, noticed this too and fixed it. will push soon too.
