### ISSUE TITLE
Any plans for adding feature of voting (e.g. like/dislike) for papers?

### ISSUE THREAD

**Issue by andreas-bulling** [karpathy/arxiv-sanity-preserver#8]
Again, would be nice to be able to rank/sort papers in a distributed fashion, e.g. among members of a research group. The more likes a paper collects the more likely it is to be discussed in the next reading group or the like.

**Comment by karpathy** [comment]
I see, you're imagining a within-a-group system, so these would not be visible to general visitor of the site, only to people of some group.

**Comment by andreas-bulling** [comment]
I was indeed but this could be very nice also for a public system, extending towards a reviewing interface
maybe similar to http://theoj.org/

**Comment by andreas-bulling** [comment]
I was indeed but could also be interesting as a feature for a public site

**Comment by MartinThoma** [comment]
@andreas-bulling I think that would only be interesting if you could see who was voting (e.g. by connecting to http://orcid.org/). A vote by random people from the internet is probably not worth so much whereas votes by Hinton, Bengio, LeCun in deep learning would be worth a lot more.

A similar idea would be to get reviews. Sites I have heard about (but not used so far) are:

* https://publons.com/
* https://pubpeer.com/

**Comment by pgericson** [comment]
@MartinThoma You mean e.g. use the [h-index](https://scholar.google.dk/intl/en/scholar/metrics.html#metrics) from Google Scholar to use as the weight on the vote?

**Comment by MartinThoma** [comment]
@pgericson I was rather thinking of just the possibility to get a list of who has voted (similar to facebook likes). However, I think not showing the number of people who have voted but a h-index weighted score would be much better.

**Comment by karpathy** [comment]
Upvoting of papers is now implemented as people adding papers to their library. There will be no downvoting. Closing issue.
