### ISSUE TITLE
Blocked by arxiv?

### ISSUE THREAD

**Issue by yo-shavit** [karpathy/arxiv-sanity-preserver#80]
I'm trying to do a study of texts of ML papers, and am using these scripts to acquire paper texts. After running download_pdfs.py (with about 20000 candidate papers acquired using fetch_papers.py) I was seemingly blocked by arxiv after downloading 1201 papers.
Has anyone experienced this sort of rate-limiting, not during fetch_papers but during download_pdfs? I can't access arxiv at all (including for my regular research), and am wondering whether this sort of blocking goes away after a little while, or if I need to start worrying.
![screen shot 2017-05-22 at 12 55 39 pm](https://cloud.githubusercontent.com/assets/4855927/26319707/0eb4e6b8-3eee-11e7-9717-7960d3eb51f1.png)
Thanks!

**Comment by yo-shavit** [comment]
Ok, it reset itself after ~20 minutes and now I can access the site again.
I'm leaving this here as a disclaimer for anyone running download_pdfs.py - arxiv might get angry with you after a while!

**Comment by karelin** [comment]
Just a note: arXiv.org recommends to use S3 download (payment necessary) for bulk PDF/source access: https://arxiv.org/help/bulk_data_s3
