### ISSUE TITLE
Feature request: allow export of bibtex file for citations

### ISSUE THREAD

**Issue by kirk86** [karpathy/arxiv-sanity-preserver#88]
Hi, thanks for this great work. I was wondering if it would be possible to add the ability for the users to export the saved papers in their libraries as bibtex file for later reference. This should be fairly easy to achieve if we utilize the `https://arxiv2bibtex.org`. Basically for each user loop over the papers in their library send their id's one by one to `arxiv2bibtex.org` read the text in the frame or the textbox and save it in a file. We could even use `http://ams.org/mathscinet/` to find the correct citation information.

**Comment by heytitle** [comment]
If you're using Chrome,  one way that you could do is using  [Zotero](https://www.zotero.org/download/) and Zotero Connector to save papers from `http://www.arxiv-sanity.com/library` to Zotero app and export `bibtex` from there.

**Comment by kirk86** [comment]
@heytitle thanks for the suggestion but do you have to do it manually i.e. for each paper in the `http://www.arxiv-sanity.com/library` add it to zotero and then export? that would be cumbersome. Is the there a possibility to add all the papers in `http://www.arxiv-sanity.com/library` to zotero library and then export to bibtex?

**Comment by heytitle** [comment]
I think Zotero extension allows you to do that. For example, I have 3 papers in my library. Once I click Zotero plugin, it will ask which paper I want to add to Zotero.
![image](https://user-images.githubusercontent.com/1214890/29402241-91bb862c-8334-11e7-8dc8-3afa62e79614.png)

**Comment by kirk86** [comment]
@heytitle awesome 👍 thanks for letting me know. I'll close this issue since it can be completed with third party tools.
